{
    "related_post": {
        "ts": "2020-05-30T21:56:59.981000",
        "user": "Keyla",
        "text": "@Nitro the issue there is that it can't find the pip3 command. https://stackoverflow.com/questions/23708898/pipisnotrecognizedasaninternalorexternalcommand",
        "conversation_id": "1656",
        "index": 5
    },
    "so_post": {
        "ts": "2020-05-30T21:56:59.981000",
        "user": "Keyla",
        "text": "@Nitro the issue there is that it can't find the pip3 command. https://stackoverflow.com/questions/23708898/pipisnotrecognizedasaninternalorexternalcommand",
        "conversation_id": "1656",
        "index": 5
    },
    "category": "Other",
    "comments": "ooc",
    "meta": {
        "start_date": "2020-05-01T00:00:12.573000",
        "end_time": null,
        "channel_name": "python-general",
        "team_domain": "Python",
        "count": 97711
    }
}