{
    "related_post": {
        "ts": "2020-01-22T10:14:52.945000",
        "user": "Thayne",
        "text": "https://stackoverflow.com/questions/59842600/importerrorcannotimportnamesourcedistributionfrompipinternaldistrib",
        "conversation_id": "890",
        "index": 37
    },
    "so_post": {
        "ts": "2020-01-22T10:14:52.945000",
        "user": "Thayne",
        "text": "https://stackoverflow.com/questions/59842600/importerrorcannotimportnamesourcedistributionfrompipinternaldistrib",
        "conversation_id": "890",
        "index": 37
    },
    "category": "Other",
    "comments": "ooc",
    "meta": {
        "start_date": "2020-01-01T00:01:01.257000",
        "end_time": null,
        "channel_name": "python-general",
        "team_domain": "Python",
        "count": 46313
    }
}